reactives <- reactiveValues(
    logbook = list(),# record data manipulation steps
    update_plots = NULL,  # show plots/tables
    signal_df = NULL,  # signal data frame
    derivative_df = NULL,  # derivative data frame
    signal_df_fitted = NULL,  # fitted signal data frame
    signal_df_scaled = NULL,  # scaled signal data frame
    signal_df_fitted_scaled = NULL,  # fitted scaled signal data frame
    find_initial_params = TRUE, # trigger to find initial params
    scaled_tab_shown = FALSE, # whether the scaled tab is shown
    n_rows_conditions_table = 24, # number of rows in the conditions table (default 24, can be modified)
    tm_value = NULL, # Tm value - if given, used as fixed param
    dh_value = NULL, # DH value - if given, used as fixed param
    cp_value = NULL, # Cp value - if given, used as fixed param
    fix_cp_option='auto_cp_bounds', # option to fix Cp value or set bounds
    fix_tm_option='auto_tm_bounds', # option to fix Tm value or set bounds
    fix_dh_option='auto_dh_bounds', # option to fix DH value or set bounds
    tm_low_bound = 60,  # Tm lower bound
    tm_upp_bound = 130, # Tm upper bound
    dh_low_bound = 10, # DH lower bound
    dh_upp_bound = 450, # DH upper bound
    cp_low_bound = 0.1, # Cp lower bound
    cp_upp_bound = 6, # Cp upper bound
    font_size = 16, # default font size for plots
    legend_x_pos = 1, # default legend x position
    legend_y_pos = 1, # default legend y position
    show_x_grid = FALSE, # whether to show x grid
    show_y_grid = FALSE,  # whether to show y grid
    marker_size = 7, # default marker size
    color_bar_orientation = 'horizontal', # default color bar orientation
    color_bar_length = 0.5, # default color bar length
    max_points = 2000, # maximum number of points to plot
    file_type = 'png',
    line_width = 3, # default line width for plots
    plot_width = 18, # default plot width
    plot_height = 11, # default plot height
    # Unified plot configuration (used for both regular and fit plots)
    plot_width_val = 1000, # plot width in pixels
    plot_height_val = 600, # plot height in pixels
    plot_type_val = 'png', # plot type
    plot_axis_size_val = 14, # axis size
    x_legend_pos_val = 1, # x legend position
    y_legend_pos_val = 1, # y legend position
    color_bar_length_val = 0.5, # color bar length
    color_bar_orientation_val = 'horizontal', # color bar orientation
    show_colorbar_val = TRUE, # show colorbar
    show_grid_x_val = FALSE, # show x grid
    show_grid_y_val = FALSE, # show y grid
    plot_marker_size_val = 5, # marker size
    plot_line_width_val = 2, # line width
    max_points_val = 2000, # max points to display
    n_xticks_val = 4, # number of ticks on x-axis
    n_yticks_val = 3, # number of ticks on y-axis
    tick_length_val = 8, # tick length
    tick_width_val = 2 # tick width
)

